import type { Metadata } from "next";
import "./globals.css";
// import { ApolloWrapper } from "../lib/apollo-wrapper";
import { SocketProvider } from "../lib/socket-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SocketProvider>
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
